### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by JonasFranzDEV** [Zitrone44/zlnk#2]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError("entity not found")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
occures on startup at Fedora 27.

Redis server info:
```
# Server
redis_version:4.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:da1d8b9b09457ab2
redis_mode:standalone
os:Linux 4.15.15-300.fc27.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.3.1
process_id:29082
run_id:8d06f2b441fd3aebe034cf1be4c6ae5114ac903c
tcp_port:6379
uptime_in_seconds:149
uptime_in_days:0
hz:10
lru_clock:14618721
executable:/usr/bin/redis-server
config_file:/etc/redis.conf
```

**Comment by Zitrone44** [comment]
Make sure you have the file `GeoLite2-Country.mmdb` in the same directory as the zlnk executable.

If not you can download it from https://dev.maxmind.com/geoip/geoip2/geolite2/.

**Comment by Zitrone44** [comment]
I have improved the error message in release [v0.4.4](https://github.com/Zitrone44/zlnk/releases/tag/v0.4.4)  so that it now is
```
thread 'main' panicked at 'Failed to Load "./GeoLite2-Country.mmdb"!: IoError("entity not found")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
This should be more useful.

----

I will close this issue now. If you encounter any other error while using ZLNK fell free to open a new issue.
